version: '3.8'

services:
  backend:
    container_name: books-backend
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "49000"              # expose to other containers
    env_file:
      - .env.prod
    restart: always
    networks:
      - app-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    container_name: nginx-proxy
    image: nginx:latest
    ports:
      - "80:80"               # public HTTP port
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html:/usr/share/nginx/html # ✅ Correctly mount the HTML folder
    depends_on:
      - backend
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
